2025-07-12 18:59:44 [ERROR]: 请求处理错误:
TypeError: this.db.defineCommand is not a function
    at new Limiter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/async-ratelimiter@1.6.1/node_modules/async-ratelimiter/src/index.js:91:15)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:73:17)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-convert@2.0.0/node_modules/koa-convert/index.js:42:43
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:65:19)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
{
  "error": "this.db.defineCommand is not a function",
  "url": "/api/v1/user/info",
  "method": "GET",
  "ip": "::1",
  "userAgent": "curl/8.7.1"
}
2025-07-12 18:59:52 [ERROR]: 请求处理错误:
TypeError: this.db.defineCommand is not a function
    at new Limiter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/async-ratelimiter@1.6.1/node_modules/async-ratelimiter/src/index.js:91:15)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:73:17)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-convert@2.0.0/node_modules/koa-convert/index.js:42:43
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:65:19)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
{
  "error": "this.db.defineCommand is not a function",
  "url": "/api/v1/song/hot",
  "method": "GET",
  "ip": "::1",
  "userAgent": "curl/8.7.1"
}
2025-07-12 19:00:20 [ERROR]: 请求处理错误:
TypeError: this.db.defineCommand is not a function
    at new Limiter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/async-ratelimiter@1.6.1/node_modules/async-ratelimiter/src/index.js:91:15)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:73:17)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-convert@2.0.0/node_modules/koa-convert/index.js:42:43
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:65:19)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
{
  "error": "this.db.defineCommand is not a function",
  "url": "/api/v1/auth/register",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 19:01:08 [ERROR]: 请求处理错误:
TypeError: this.db.defineCommand is not a function
    at new Limiter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/async-ratelimiter@1.6.1/node_modules/async-ratelimiter/src/index.js:91:15)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:73:17)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-convert@2.0.0/node_modules/koa-convert/index.js:42:43
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:65:19)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
{
  "error": "this.db.defineCommand is not a function",
  "url": "/api/v1",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
}
2025-07-12 19:01:08 [ERROR]: 请求处理错误:
TypeError: this.db.defineCommand is not a function
    at new Limiter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/async-ratelimiter@1.6.1/node_modules/async-ratelimiter/src/index.js:91:15)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:73:17)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-convert@2.0.0/node_modules/koa-convert/index.js:42:43
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:65:19)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co@4.6.0/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
{
  "error": "this.db.defineCommand is not a function",
  "url": "/favicon.ico",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
}
2025-07-12 19:03:24 [ERROR]: 请求处理错误:
Error: 用户名已存在
    at UserService.createUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/user-service.js:86:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async register (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:44:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名已存在",
  "url": "/api/v1/auth/register",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 19:03:59 [ERROR]: 请求处理错误:
Error: 邮箱已存在
    at UserService.createUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/user-service.js:93:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async register (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:44:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "邮箱已存在",
  "url": "/api/v1/auth/register",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 20:23:55 [ERROR]: 请求处理错误:
Error: 用户名不能为空
    at login (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:79:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名不能为空",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 20:27:58 [ERROR]: 请求处理错误:
Error: 用户名或密码错误
    at UserService.validateUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/user-service.js:187:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async login (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:83:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名或密码错误",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::1",
  "userAgent": "curl/8.7.1"
}
2025-07-12 20:30:24 [ERROR]: 请求处理错误:
Error: 无效的访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:37:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "无效的访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 20:34:43 [ERROR]: 请求处理错误:
Error: 刷新令牌不能为空
    at refreshToken (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:114:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:11)
{
  "error": "刷新令牌不能为空",
  "url": "/api/v1/auth/refresh",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 20:35:35 [ERROR]: 请求处理错误:
Error: 刷新令牌不能为空
    at refreshToken (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:114:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:11)
{
  "error": "刷新令牌不能为空",
  "url": "/api/v1/auth/refresh",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 21:57:54 [ERROR]: 请求处理错误:
Error: "keyword" is not allowed to be empty
    at getUserList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/user-controller.js:164:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
{
  "error": "\"keyword\" is not allowed to be empty",
  "url": "/api/v1/user/list",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-12 22:00:21 [ERROR]: 请求处理错误:
Error: "keyword" is not allowed to be empty
    at getUserList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/user-controller.js:164:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
{
  "error": "\"keyword\" is not allowed to be empty",
  "url": "/api/v1/user/list",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-13 08:39:55 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-13 08:47:47 [ERROR]: 请求处理错误:
Error: 头像URL格式错误
    at uploadAvatar (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/user-controller.js:98:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
{
  "error": "头像URL格式错误",
  "url": "/api/v1/user/avatar",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-13 09:00:55 [ERROR]: 请求处理错误:
Error: Unexpected field
    at makeError (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@1.3.0/node_modules/multer/lib/make-error.js:12:13)
    at wrappedFileFilter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@1.3.0/node_modules/multer/index.js:40:19)
    at Busboy.<anonymous> (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@1.3.0/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (node:events:507:28)
    at Busboy.emit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@0.2.14/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@0.2.14/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (node:events:507:28)
    at HeaderParser.<anonymous> (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/dicer@0.2.5/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (node:events:507:28)
    at HeaderParser._finish (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/dicer@0.2.5/node_modules/dicer/lib/HeaderParser.js:68:8)
{
  "error": "Unexpected field",
  "url": "/api/v1/user/avatar",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-13 09:03:32 [ERROR]: 请求处理错误:
MulterError: Unexpected field
    at wrappedFileFilter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@2.0.1/node_modules/multer/index.js:40:19)
    at Multipart.<anonymous> (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@2.0.1/node_modules/multer/lib/make-middleware.js:123:7)
    at Multipart.emit (node:events:507:28)
    at HeaderParser.cb (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:358:14)
    at HeaderParser.push (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:162:20)
    at SBMH.ssCb [as _cb] (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:394:37)
    at feed (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/streamsearch@1.1.0/node_modules/streamsearch/lib/sbmh.js:248:10)
    at SBMH.push (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/streamsearch@1.1.0/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:570:12)
{
  "error": "Unexpected field",
  "url": "/api/v1/user/avatar",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-13 09:04:20 [ERROR]: 请求处理错误:
Error: 无效的访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:37:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:11)
{
  "error": "无效的访问令牌",
  "url": "/api/v1/user/avatar",
  "method": "POST",
  "ip": "::1",
  "userAgent": "curl/8.7.1"
}
2025-07-13 09:09:00 [ERROR]: 请求处理错误:
MulterError: Unexpected field
    at wrappedFileFilter (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@2.0.1/node_modules/multer/index.js:40:19)
    at Multipart.<anonymous> (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/multer@2.0.1/node_modules/multer/lib/make-middleware.js:123:7)
    at Multipart.emit (node:events:507:28)
    at HeaderParser.cb (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:358:14)
    at HeaderParser.push (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:162:20)
    at SBMH.ssCb [as _cb] (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:394:37)
    at feed (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/streamsearch@1.1.0/node_modules/streamsearch/lib/sbmh.js:248:10)
    at SBMH.push (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/streamsearch@1.1.0/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/busboy@1.6.0/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:570:12)
{
  "error": "Unexpected field",
  "url": "/api/v1/user/avatar",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 09:52:04 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-14 09:52:41 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-14 10:01:35 [ERROR]: 请求处理错误:
Error: 歌曲不存在
    at getSongById (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:27:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "歌曲不存在",
  "url": "/api/v1/song/detail/id=1889155784",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:03:58 [ERROR]: 请求处理错误:
Error: 艺术家不存在
    at SongService.createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:129:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:38:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "艺术家不存在",
  "url": "/api/v1/song/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:05:40 [ERROR]: 请求处理错误:
Error: 艺术家不存在
    at SongService.createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:129:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:38:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "艺术家不存在",
  "url": "/api/v1/song/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:05:50 [ERROR]: 请求处理错误:
Error: 专辑不存在
    at SongService.createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:136:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:38:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "专辑不存在",
  "url": "/api/v1/song/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:08:37 [ERROR]: 请求处理错误:
Error: 歌曲不存在
    at SongService.updateSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:182:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async updateSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:50:18)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "歌曲不存在",
  "url": "/api/v1/song/update/270191871",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:16:54 [ERROR]: 请求处理错误:
Error: 歌曲不存在
    at SongService.playSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:270:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async playSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:71:5)
    at async optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "歌曲不存在",
  "url": "/api/v1/song/play/2701918718",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:23:54 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:11)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/song/like/1456890009",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:24:07 [ERROR]: 请求处理错误:
Error: 已经喜欢该歌曲
    at SongService.likeSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/song-service.js:428:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async likeSong (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/song-controller.js:103:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已经喜欢该歌曲",
  "url": "/api/v1/song/like/1456890009",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:38:08 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:11)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/playlist/remove/4",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:46:22 [ERROR]: 请求处理错误:
Error: 不能收藏自己的歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:313:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "不能收藏自己的歌单",
  "url": "/api/v1/playlist/collect/1",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 10:48:40 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 11:12:29 [ERROR]: 请求处理错误:
TypeError: createResponse is not a function
    at search (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/search-controller.js:37:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "createResponse is not a function",
  "url": "/api/v1/search?keyword=%E5%91%A8%E6%9D%B0%E4%BC%A6",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 11:14:14 [ERROR]: 请求处理错误:
TypeError: createResponse is not a function
    at search (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/search-controller.js:37:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "createResponse is not a function",
  "url": "/api/v1/search?keyword=%E5%91%A8%E6%9D%B0%E4%BC%A6",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 13:41:56 [ERROR]: 请求处理错误:
Error: 搜索记录不存在或已被删除
    at deleteSearchHistory (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/search-controller.js:293:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "搜索记录不存在或已被删除",
  "url": "/api/v1/search/history/delete",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:05:32 [ERROR]: 请求处理错误:
Error: 已经关注过该用户
    at FollowService.followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/follow-service.js:32:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:17:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已经关注过该用户",
  "url": "/api/v1/social/follow/2",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:06:03 [ERROR]: 请求处理错误:
Error: 不能关注自己
    at FollowService.followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/follow-service.js:14:13)
    at followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:17:25)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "不能关注自己",
  "url": "/api/v1/social/follow/1",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:06:20 [ERROR]: 请求处理错误:
Error: 已经关注过该用户
    at FollowService.followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/follow-service.js:32:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async followUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:17:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已经关注过该用户",
  "url": "/api/v1/social/follow/2",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:07:10 [ERROR]: 请求处理错误:
Error: 不能取消关注自己
    at FollowService.unfollowUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/follow-service.js:49:13)
    at unfollowUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:28:25)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "不能取消关注自己",
  "url": "/api/v1/social/unfollow/1",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:07:14 [ERROR]: 请求处理错误:
Error: 未关注该用户
    at FollowService.unfollowUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/follow-service.js:61:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async unfollowUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:28:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未关注该用户",
  "url": "/api/v1/social/unfollow/2",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:14:33 [ERROR]: 请求处理错误:
TypeError: Cannot read properties of undefined (reading 'transaction')
    at SocialService.addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:186:41)
    at addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:136:41)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "Cannot read properties of undefined (reading 'transaction')",
  "url": "/api/v1/social/comment",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:16:20 [ERROR]: 请求处理错误:
TypeError: Cannot read properties of undefined (reading 'transaction')
    at SocialService.addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:186:41)
    at addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:136:41)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "Cannot read properties of undefined (reading 'transaction')",
  "url": "/api/v1/social/comment",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:30:21 [ERROR]: 请求处理错误:
Error: 歌曲不存在
    at SocialService.addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:222:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async addComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:136:21)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "歌曲不存在",
  "url": "/api/v1/social/comment",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:31:38 [ERROR]: 请求处理错误:
Error: 评论不存在
    at SocialService.deleteComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:304:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async deleteComment (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:147:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "评论不存在",
  "url": "/api/v1/social/comment/delete/3",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:34:56 [ERROR]: 请求处理错误:
Error: 笔记不存在
    at SocialService.addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:24:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:93:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "笔记不存在",
  "url": "/api/v1/social/like",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:36:25 [ERROR]: 请求处理错误:
Error: 笔记不存在
    at SocialService.removeLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:78:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async removeLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:104:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "笔记不存在",
  "url": "/api/v1/social/unlike",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:36:48 [ERROR]: 请求处理错误:
Error: 未点赞过
    at SocialService.removeLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:97:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async removeLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:104:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未点赞过",
  "url": "/api/v1/social/unlike",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:39:46 [ERROR]: 请求处理错误:
Error: 无效的评论类型
    at SocialService.getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:145:13)
    at getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:125:40)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "无效的评论类型",
  "url": "/api/v1/social/comments",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:40:00 [ERROR]: 请求处理错误:
Error: 无效的评论类型
    at SocialService.getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:145:13)
    at getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:125:40)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "无效的评论类型",
  "url": "/api/v1/social/comments",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:40:55 [ERROR]: 请求处理错误:
Error: 无效的评论类型
    at SocialService.getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:145:13)
    at getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:125:40)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "无效的评论类型",
  "url": "/api/v1/social/comments",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:41:23 [ERROR]: 请求处理错误:
Error: 无效的评论类型
    at SocialService.getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:145:13)
    at getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:125:40)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "无效的评论类型",
  "url": "/api/v1/social/comments",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 14:41:47 [ERROR]: 请求处理错误:
Error: 无效的评论类型
    at SocialService.getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:145:13)
    at getCommentList (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:125:40)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at optionalAuth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:72:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
{
  "error": "无效的评论类型",
  "url": "/api/v1/social/comments?targetId=2718176688",
  "method": "GET",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:04:15 [ERROR]: 请求处理错误:
Error: 指定的歌曲不存在
    at NoteService.createNote (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/note-service.js:148:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createNote (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/note-controller.js:40:18)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "指定的歌曲不存在",
  "url": "/api/v1/note/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:04:20 [ERROR]: 请求处理错误:
TypeError: Cannot read properties of undefined (reading 'transaction')
    at NoteService.createNote (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/note-service.js:153:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createNote (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/note-controller.js:40:18)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "Cannot read properties of undefined (reading 'transaction')",
  "url": "/api/v1/note/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:14:09 [ERROR]: 请求处理错误:
SyntaxError: invalid JSON, only supports object and array
    at parse (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co-body@6.2.0/node_modules/co-body/lib/json.js:57:13)
    at module.exports [as json] (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/co-body@6.2.0/node_modules/co-body/lib/json.js:43:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async parseBody (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:87:14)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:67:19)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "invalid JSON, only supports object and array",
  "url": "/api/v1/note/create",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:24:06 [ERROR]: 请求处理错误:
Error: 笔记不存在
    at SocialService.addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:24:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:93:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "笔记不存在",
  "url": "/api/v1/social/like",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:43:12 [ERROR]: 请求处理错误:
Error: 已经点赞过了
    at SocialService.addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:43:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:93:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已经点赞过了",
  "url": "/api/v1/social/like",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-14 15:47:50 [ERROR]: 请求处理错误:
Error: 已经点赞过了
    at SocialService.addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/social-service.js:43:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async addLike (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/social-controller.js:93:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已经点赞过了",
  "url": "/api/v1/social/like",
  "method": "POST",
  "ip": "::1",
  "userAgent": "Apifox/1.0.0 (https://apifox.com)"
}
2025-07-16 14:59:34 [ERROR]: 请求处理错误:
Error: 用户名已存在
    at UserService.createUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/user-service.js:86:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async register (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:50:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名已存在",
  "url": "/api/v1/auth/register",
  "method": "POST",
  "ip": "::1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 15:12:21 [ERROR]: 请求处理错误:
Error: 用户名或密码错误
    at UserService.validateUser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/user-service.js:187:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async login (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/auth-controller.js:89:18)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名或密码错误",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 17:18:47 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 17:21:07 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 17:21:23 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:06:04 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-16 20:07:44 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:10:20 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:10:31 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:11:07 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:13:59 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:21:11 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:30:34 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:34:29 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:37:06 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:43:53 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:55:34 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 20:58:07 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:02:14 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:09:50 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:23:56 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:28:38 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:30:09 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:35:47 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:40:26 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:48:19 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:52:31 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 21:56:08 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-16 22:29:20 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 08:23:38 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-17 08:36:19 [ERROR]: 请求处理错误:
Error: 缺少访问令牌
    at auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:13:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async ratelimit (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-ratelimit@5.1.0/node_modules/koa-ratelimit/index.js:100:33)
{
  "error": "缺少访问令牌",
  "url": "/api/v1/auth/me",
  "method": "GET",
  "ip": "::1",
  "userAgent": "curl/8.7.1"
}
2025-07-17 10:40:33 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 10:40:34 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 10:40:34 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 10:40:36 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 14:23:17 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-17 16:13:09 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 16:13:09 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 16:13:32 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 16:13:33 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 16:13:34 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-17 16:13:56 [ERROR]: 请求处理错误:
Error: 已收藏该歌单
    at PlaylistService.collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/services/playlist-service.js:322:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectPlaylist (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/playlist-controller.js:107:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "已收藏该歌单",
  "url": "/api/v1/playlist/collect/3",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-18 09:33:49 [ERROR]: 请求处理错误:
Error: 搜索记录不存在或已被删除
    at deleteSearchHistory (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/search-controller.js:293:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "搜索记录不存在或已被删除",
  "url": "/api/v1/search/history/delete",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-18 09:33:50 [ERROR]: 请求处理错误:
Error: 搜索记录不存在或已被删除
    at deleteSearchHistory (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/controllers/search-controller.js:293:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-app/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-app/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "搜索记录不存在或已被删除",
  "url": "/api/v1/search/history/delete",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-21 09:13:07 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-21 10:55:03 [ERROR]: 请求处理错误:
Error: "oldPassword" is not allowed
    at changePassword (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/user-controller.js:79:13)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at auth (/Users/cloud/Documents/Project/Harmony/my-server/src/middleware/auth.js:34:11)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:15)
{
  "error": "\"oldPassword\" is not allowed",
  "url": "/api/v1/user/change-password",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-21 15:47:36 [ERROR]: 请求处理错误:
Error: 未喜欢该歌曲
    at SongService.unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/services/song-service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/song-controller.js:114:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未喜欢该歌曲",
  "url": "/api/v1/song/unlike/21234462",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-22 09:00:37 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-22 15:08:56 [ERROR]: 请求处理错误:
Error: 未喜欢该歌曲
    at SongService.unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/services/song-service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/song-controller.js:114:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未喜欢该歌曲",
  "url": "/api/v1/song/unlike/2701918717",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-22 15:08:57 [ERROR]: 请求处理错误:
Error: 未喜欢该歌曲
    at SongService.unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/services/song-service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/song-controller.js:114:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未喜欢该歌曲",
  "url": "/api/v1/song/unlike/2701918717",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-22 15:33:09 [ERROR]: 请求处理错误:
Error: 未喜欢该歌曲
    at SongService.unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/services/song-service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async unlikeSong (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/song-controller.js:114:5)
    at async auth (/Users/cloud/Documents/Project/Harmony/my-server/src/middleware/auth.js:34:5)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "未喜欢该歌曲",
  "url": "/api/v1/song/unlike/2122108982",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-23 14:31:48 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-23 19:22:59 [ERROR]: 数据库初始化失败，应用无法启动
2025-07-23 21:45:46 [ERROR]: 请求处理错误:
Error: 用户名或密码错误
    at UserService.validateUser (/Users/cloud/Documents/Project/Harmony/my-server/src/services/user-service.js:187:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async login (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/auth-controller.js:89:18)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名或密码错误",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-24 13:10:46 [ERROR]: 请求处理错误:
Error: 用户名或密码错误
    at UserService.validateUser (/Users/cloud/Documents/Project/Harmony/my-server/src/services/user-service.js:187:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async login (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/auth-controller.js:89:18)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名或密码错误",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
2025-07-24 13:12:07 [ERROR]: 请求处理错误:
Error: 用户名或密码错误
    at UserService.validateUser (/Users/cloud/Documents/Project/Harmony/my-server/src/services/user-service.js:187:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async login (/Users/cloud/Documents/Project/Harmony/my-server/src/controllers/auth-controller.js:89:18)
    at async serve (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-static@5.0.0/node_modules/koa-static/index.js:53:9)
    at async bodyParser (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)
    at async logger (/Users/cloud/Documents/Project/Harmony/my-server/node_modules/.pnpm/koa-logger@3.2.1/node_modules/koa-logger/index.js:67:7)
{
  "error": "用户名或密码错误",
  "url": "/api/v1/auth/login",
  "method": "POST",
  "ip": "::ffff:127.0.0.1",
  "userAgent": "libcurl-agent/1.0"
}
